spring:
  username: user
  password: pass
  url: jdbc:h2:./src/main/resources/task56/h2
  driver-class-name: org.h2.Driver

services-uri:
  get-all-products: http://localhost:8080/product/getByUser/
  get-product-by-id: http://localhost:8080/product/getById/
  debit-product: http://localhost:8080/product/debit
  credit-product: http://localhost:8080/product/credit