package ru.cource.task2;

public enum JobTitle {WEB_DEVELOPER, SOFTWARE_ENGINEER, SOFTWARE_DEVELOPER, FRONT_END_DEVELOPER, NETWORK_ENGINEER, JAVA_DEVELOPER, IOS_DEVELOPER, SQL_DEVELOPER, ANDROID_DEVELOPER, SALESFORCE_DEVELOPER, ENGINEER}