spring:
  datasource:
    username: user
    password: pass
    url: jdbc:h2:./src/main/resources/task7/h2
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: false
        order_inserts: true
        jdbc.batch_size: 100
        hbm2ddl:
          auto: validate
  flyway:
    enabled: true
    validate-on-migrate: false

services-uri:
  get-all-products: http://localhost:8080/product/getByUser/
  get-product-by-id: http://localhost:8080/product/getById/
  debit-product: http://localhost:8080/product/debit
  credit-product: http://localhost:8080/product/credit